### ISSUE TITLE
Support single package upgrade semantic

### ISSUE THREAD

**Issue by uranusjr** [sarugaku/resolvelib#1]
The resolver should be able to accept an already resolved graph, and start resolving from there (instead of a new graph). Upgrade semantic can probably be done on the callee side: Remove a vertex from an existing graph [*], and send it to the resolver with the requirements (including the package to be upgraded) to upgrade. I don’t have a proof, but this should work.

[*]: The vertex’s children should not be removed (although edges to it obviously need to be severed). The resolver will probably need to gain a cleanup phase to remove orphan vertices (vertices without any parents) from the graph after resolution is done.

**Comment by uranusjr** [comment]
This can be done entirely in the provider. From the CocoaPods tests:

https://github.com/sarugaku/resolvelib/blob/fe8f0dc2efe1af0f6eefb3ff24d9c21de010f8cc/tests/functional/cocoapods/test_resolvers_cocoapods.py#L126-L133

The provider can feed the already-resolved data to the resolver by giving it only one candidate (the resolved one). If upgrades may be needed, it can still give it other choices, but simply putting the already-resolved one at the top (most preferred).

Graph and mapping cleanup are already implemented in #22. Therefore the only benefit of feeding a pre-resolved graph is only *possible* optimisation (the resolver don’t need to build a graph from scratch). It might still be a good idea, but would be very low priority at the moment. Closing.

**Comment by pradyunsg** [comment]
Yay! You're reaching the same conclusions as me! ^>^
