### ISSUE TITLE
Let's move this to the `pypa` organisation?

### ISSUE THREAD

**Issue by pradyunsg** [sarugaku/resolvelib#102]
I think it makes sense to do this, given that this is used by pip.

**Comment by uranusjr** [comment]
No strong thoughts. Originally this was designed as a generic dependency resolution library, but I guess no many people really need fancy dependency resolution outside of the packaging community.

**Comment by pfmoore** [comment]
Agreed, if this is intended to be generic, putting it under PyPA is probably wrong. But if it *is* intended to be generic, the docs could do with making that clearer. The "Terminology" section in particular is very packaging-focused.

(I will say that I can't think immediately of a non-packaging use for this - maybe adding an example would be good?)

**Comment by pradyunsg** [comment]
I think this is fairly closely related to pip/packaging use cases, but if folks feel otherwise, I don't mind withdrawing this suggestion.

Please feel free to close this, if that's the case. :)

**Comment by pradyunsg** [comment]
Well, I'll close this out. :P
