### ISSUE TITLE
Sdist releases on pypi.org do not contain files required for tests 

### ISSUE THREAD

**Issue by dvzrv** [sarugaku/resolvelib#108]
Hi! I'm currently looking into updating this package for Arch Linux.
I noticed that the pypi.org sdist tarballs do not contain files required for testing. From a downstream perspective it is always good to be able to rely on sdist tarballs for running tests as well.

It would be awesome if they could be added! Thank you! :)

**Comment by uranusjr** [comment]
Personally I prefer to not put tests in sdists since they’re dead weight to most people. What prevents the Git tags (and artifacts generated by GitHub against them) from being usable?

**Comment by pradyunsg** [comment]
Closing since I'm in agreement.
