### ISSUE TITLE
Drop support for Python prior to 3.7

### ISSUE THREAD

**Issue by frostming** [sarugaku/resolvelib#116]
I think it's time to drop support for Python versions prior to 3.7.

/cc @uranusjr @pradyunsg

**Comment by uranusjr** [comment]
Yes

**Comment by uranusjr** [comment]
This is mostly plain logic and the 2/3 difference is close to none. Perhaps the only thing that matters in typing?

**Comment by frostming** [comment]
> Perhaps the only thing that matters is typing?

Yes, and CI infrastructures don't support 2.7 well.

**Comment by frostming** [comment]
Duplicate with #98
