### ISSUE TITLE
Awkward wording in docstring for `find_matches()`

### ISSUE THREAD

**Issue by brettcannon** [sarugaku/resolvelib#137]
The docstring says the `identifier` parameter "identifies the dependency matches of which should be returned." Is this trying to say it "it identifies the dependency for which matches should be returned"?

**Comment by uranusjr** [comment]
It’s trying to say (iirc) for each candidate returned by `find_matches`, `identify(candidate)` should return the same value as `identifier`. A reword would be helpful…

**Comment by brettcannon** [comment]
Does that mean `identify()` can be called on a candidate as well? The `identify()` docstring only mentions requirements:

https://github.com/sarugaku/resolvelib/blob/77b256cdfb747e86112025d75cd698861ce355a5/src/resolvelib/providers.py#L5-L9

The typing suggests it can be either, but the README says " "requirement" ... SHOULD NOT be used when describing a Candidate, to avoid confusion", so that docstring might also be misleading.

And I'm happy to submit a PR to clear up the wording on all of this once I understand exactly what's expected.

**Comment by uranusjr** [comment]
Yes; the argument is called `requirement_or_candidate` (and typed as `Union[RT, CT]`). The docstring does indeed need some fixup.

**Comment by brettcannon** [comment]
I'll create a PR to try to clarify both docstrings.

**Comment by brettcannon** [comment]
https://github.com/sarugaku/resolvelib/pull/138 is my attempt to clarify things.
