### ISSUE TITLE
Request: New Release

### ISSUE THREAD

**Issue by notatallshaw** [sarugaku/resolvelib#159]
Hi all, given the recent fixes to backjumping I am requesting a new release. I would like to vendor resolvelib early into pip comfortably before 24.3 so it can be sufficently tested.

I also notice it's been over a year since release, so there are quite a few PRs that have been merged:

e4de27e - Merge pull request #158 from notatallshaw/add-unvisited-tests
58c5d90 - Merge pull request #155 from notatallshaw/skip-backjumping-when-name-is-not-incompatible
314dde4 - Merge pull request #157 from notatallshaw/replace-setuptools-cfg-with-pyproject.toml
b01ff4e - Merge pull request #156 from notatallshaw/fix-up-py2index-script
ffa7199 - Merge pull request #152 from notatallshaw/fix-backjumping
adf0800 - Merge pull request #153 from notatallshaw/run-python-3.12-and-3.13-and-bump-all-versions-in-ci.yml
87c9d7b - Merge pull request #141 from hroncok/nocmmments
a062162 - Merge pull request #150 from notatallshaw/pin-black-version
995ed67 - Merge pull request #143 from notatallshaw/deduplicate-causes
044ab9f - Merge pull request #135 from sarugaku/modern-typing
6df10d7 - Merge pull request #136 from jimkring/patch-1
69d9fee - Merge pull request #138 from brettcannon/clarify-docstrings
77b256c - Merge pull request #133 from hauntsaninja/hauntsaninja-patch-1
ea4011b - Merge pull request #129 from OlenaYefymenko/122-supported-python-versions

**Comment by frostming** [comment]
@notatallshaw Thank you very much. Also, if you have time, could you add the missing news fragments? They should be located under the news/ folder

**Comment by notatallshaw** [comment]
> @notatallshaw Thank you very much. Also, if you have time, could you add the missing news fragments? They should be located under the news/ folder

I never understood how news fragments worked, I'll do a bit of reading this evening and hopefully be able to add them.

**Comment by frostming** [comment]
It seems all issues are addressed. But I don't have the permission to upload releases, nor is the token configured in the GitHub secrets. I'll leave it to @pradyunsg and @uranusjr to make a new release.

**Comment by notatallshaw** [comment]
Thanks for your assistance! 

Maybe we should expand the number of maintainers with access to upload? and also I would be happy to help maintain the project., if they would help avoid the project accidentally running out of people with access to release.

**Comment by pradyunsg** [comment]
I'll set up something like https://github.com/pypa/installer/issues/220 on there and come back here.

**Comment by frostming** [comment]
> I'll set up something like [pypa/installer#220](https://github.com/pypa/installer/issues/220) on there and come back here.

Thank you very much, I've setup an automated release workflow in #168 , and here is the info:

Repository: `pypa/resolvelib`
Workflow: `release.yml`
Environment name: `release`

**Comment by notatallshaw** [comment]
Pinging on this so it's not forgotten, I'd like to vendor resolvelib for for [pip 24.3](https://github.com/pypa/pip/issues/12941) with enough time to identify any issues I missed.

**Comment by pradyunsg** [comment]
<img width="746" alt="Screenshot 2024-09-15 at 18 33 19" src="https://github.com/user-attachments/assets/2f40a064-3bef-4d54-aa18-42219bc30a91">

Let's cut a release with a pre-release tag, wait for at least a week or so before going live with a proper release.

**Comment by frostming** [comment]
@pradyunsg sorry but the repository name is `sarugaku/resolvelib`, unless we are going to move this into pypa org?

**Comment by notatallshaw** [comment]
Is there an ETA on this?

I'm trying to assess if this can make pip 24.3 or I should reschedule the milestones for the issues on pip side to 25.0.

**Comment by uranusjr** [comment]
I think I’m going to just add @notatallshaw as a maintainer on this project (because as mentioned we are technically a separate entity 😉) unless anyone objects. @sarugaku/packaging-team

**Comment by notatallshaw** [comment]
FYI, it is now [too soon](https://github.com/pypa/pip/issues/12941#issuecomment-2404274504) before pip 24.3 release to vendor resolvelib 1.1.0 into pip.

I have been testing an example [problematic resolution](https://github.com/pypa/pip/issues/12990) in pip that currently fails to resolve (due to backtracking too far on an unimportant requirement), vendoring the resolvelib 1.1.0 release manually it turns the failed resolution into ResolutionTooDeep unless I apply additional optimizations such as https://github.com/pypa/pip/issues/12993 or https://github.com/pypa/pip/pull/12499.

I therefore think even if resolvelib 1.1.0 is released in the next week it should target pip 25.0, so there is time to vendor this release and then add additional optimizations on the pip side. I am going to move the issues I marked with milestone 24.3 to 25.0.

**Comment by pradyunsg** [comment]
<img width="735" alt="Screenshot 2024-10-10 at 23 27 36" src="https://github.com/user-attachments/assets/552c2840-8a00-417e-8734-940bb7d4ce5d">

Fixed and added @frostming to the project. @notatallshaw I couldn't find your username on pypi.org.

**Comment by notatallshaw** [comment]
Oh, fun fact, I've never had a need for a pypi.org account before: https://pypi.org/user/notatallshaw/

**Comment by notatallshaw** [comment]
FYI, I've created some simple scripts to validate changes when they are vendored into pip don't cause regressions: https://github.com/notatallshaw/Pip-Resolution-Scenarios-and-Benchmarks

I've used it to verify a PR that changes pip's preference: https://github.com/pypa/pip/pull/13017

But when I get time this week I will also use it to check against the resolvelib vendor PR: https://github.com/pypa/pip/pull/13001

**Comment by notatallshaw** [comment]
Okay, I've vendored and tested resolvelib, it's a slightly mixed bag in terms of performance, some existing `ResolutionTooDeep` errors now run fine. Whereas some existing resolutions that are slow are pushed over into `ResolutionTooDeep`. See details in https://github.com/pypa/pip/pull/13001#issuecomment-2421013955.

All that said, nothing seems wrong on resolvelib side, correctness is fixed and I don't see any showstopping bugs, I see no reason not to cut a final release.

**Comment by notatallshaw** [comment]
> I think I’m going to just add @notatallshaw as a maintainer on this project (because as mentioned we are technically a separate entity 😉) unless anyone objects. @sarugaku/packaging-team

Any update on this? I would love to be able to more directly help out.

**Comment by frostming** [comment]
@notatallshaw I've invited you as the collaborator on this project.

**Comment by notatallshaw** [comment]
Thanks!
