### ISSUE TITLE
Add abstract functional tests for the resolver

### ISSUE THREAD

**Issue by uranusjr** [sarugaku/resolvelib#16]
Look for ready-made declarative tests to run against the resolver. Some potential sources:

* [x] Swift Package Manager. Especially the [performance test inputs](https://github.com/apple/swift-package-manager/tree/master/Tests/PackageGraphPerformanceTests/Inputs). #17
* [x] CocoaPods. See [resolver integration spec](https://github.com/CocoaPods/Resolver-Integration-Specs/). #21
* [ ] [Cargo](https://github.com/rust-lang/cargo). I don’t see any serious tests though :(
* [ ] vgo. I don’t know how it works. Someone help please.
* [x] Bundler (Ruby). [Tests](https://github.com/rubygems/bundler/blob/master/spec/resolver/basic_spec.rb) and [indexes](https://github.com/rubygems/bundler/blob/master/spec/support/indexes.rb) in DSL.
* [x] Dart. [Fixtures seem to be integrated in tests.](https://github.com/dart-lang/pub/blob/master/test/version_solver_test.dart)
* [x] Poetry. [Fixtures in code.](https://github.com/python-poetry/poetry/tree/master/tests/mixology/version_solver) [Mixology too.](https://github.com/sdispater/mixology/tree/master/tests)

**Comment by pradyunsg** [comment]
suggestion: add https://github.com/CocoaPods/Resolver-Integration-Specs/ to this list.

**Comment by uranusjr** [comment]
Closing since I have exhausted all each-to-reach fixtures. Unless we want to start reimplementing tests from foreign programming languages, Swift and CocoaPods are the best we have.

**Comment by pradyunsg** [comment]
Linking to Cargo-related material:

- Docs: https://docs.rs/cargo/0.32.0/cargo/core/resolver/index.html
- Tests: https://github.com/rust-lang/cargo/blob/22a8715a8b23d1bb1e846cc1dc3c59d10c5c4106/crates/resolver-tests/tests/resolve.rs

**Comment by pradyunsg** [comment]
I can't find anything for vgo either. :(

Looking at `dep` tho:

- Docs: https://golang.github.io/dep/docs/the-solver.html (links to https://github.com/sdboyer/gps/wiki/gps-for-Contributors)
- Tests:
  - https://github.com/golang/dep/blob/5a7960a4cb82dda7253e8b3f921e394cd3c817d3/gps/solve_basic_test.go#L460
  - https://github.com/golang/dep/blob/5a7960a4cb82dda7253e8b3f921e394cd3c817d3/gps/solve_bimodal_test.go#L42
  - https://github.com/golang/dep/blob/5a7960a4cb82dda7253e8b3f921e394cd3c817d3/gps/solve_failures.go (all code) :(
