### ISSUE TITLE
Add CI and release automation

### ISSUE THREAD

**Issue by pradyunsg** [sarugaku/resolvelib#20]
Would be beneficial to the development workflow. :)

**Comment by uranusjr** [comment]
Next on my todo after pulling in test cases. I also want to modernise the metadata a bit, maybe move to Flit.

**Comment by pradyunsg** [comment]
\<shameless-plug>You can adapt the automation for CI + release + flit setup from [vendoring](https://github.com/pradyunsg/vendoring).

If you wanna build the distribution and upload from CI, that's something I'm gonna work on pretty soon FYI (either in packaging, or in vendoring, then synchronizing them both).

**Comment by uranusjr** [comment]
CI added in #23. Release automation needs some clean up, but there’s no hurry since we’re not releasing any time soon (until at least I finish with tests).

**Comment by uranusjr** [comment]
I had the automation down using invoke and parver (for version bumping). I’ll use this script manually for a while to make sure it satisfies the need, and make it fully automated (probably using GitHub Actions) afterwards.

**Comment by pradyunsg** [comment]
We have CI at this point. Closing this since release automation is something we can investigate separately.

**Comment by webknjaz** [comment]
@pradyunsg do you want a PR with secretless publishing?
