### ISSUE TITLE
Adding Python-esque test cases

### ISSUE THREAD

**Issue by pradyunsg** [sarugaku/resolvelib#27]
One of the things that can be found in zazo's issue tracker, is a bunch of Python-specific failure cases for the current pip resolver.

It might be useful to add test cases for those situations. Another case that would be really handy would be to have test cases for some successful situations, like installing `https://libraries.io/github/aws/chalice` -- which depends on 35+ packages directly, including botocore, which has 900+ releases.

**Comment by pradyunsg** [comment]
I suggest creating a script that fetches metadata from PyPI's JSON API for a package for all versions of that package, and dumps those details into a file (skipping packages without dependency metadata from the API). Then running this script for with all packages that get installed when you do `pip install chalice` will give you all the information needed to construct the test case.

**Comment by uranusjr** [comment]
> I suggest creating a script that fetches metadata from PyPI's JSON API for a package for all versions of that package, and dumps those details into a file

Many of Monilino’s test cases are built this way (from RubyGems), and I’m 100% on board. It wouldn’t be a terrible idea to read from wheels even IMO since the spec generation is a one-off event.

**Comment by pradyunsg** [comment]
https://github.com/pypa/pip/issues/7096

^ another simple-but-interesting case. :)

**Comment by uranusjr** [comment]
Note: There are some cases raised in pypa/pip#7406 as well.

**Comment by pradyunsg** [comment]
You can probably directly use https://github.com/chrahunt/packages. :)

**Comment by uranusjr** [comment]
One more pypa/pip#7714

**Comment by uranusjr** [comment]
(BTW I started implementing this in the `pypi-tests` branch.)

**Comment by pradyunsg** [comment]
File a draft PR for the WIP branch?

**Comment by pradyunsg** [comment]
One place worth "mining" is... pypa/pip#988. A *lot* of issues related to dependency resolution on pip's issue tracker were closed by cross-linking to that issue -- if you're looking for additional test cases, that'd be a good place to dig up for them.

**Comment by uranusjr** [comment]
List of cases to pull (growing):

* [x] chalice
* [ ] Two extras required separately for one package (pypa/pip#7096)
* [ ] Two entries for one package, on with extra and one without (pypa/pip#7714)
* [ ] pypa/pip#7406
    * TODO: Read the thread
* [ ] pypa/pip#988
    * TODO: Read the thread

**Comment by uranusjr** [comment]
To reproduce the virtualenv + pre-commit error:

```
$ pip install "virtualenv<20" "six<1.12.0" "tox==3.14.2"
...

$ pip install -U "tox<3.14.4" virtualenv
...
ERROR: virtualenv 20.0.3 has requirement six<2,>=1.12.0, but you'll have six 1.11.0 which is incompatible.
...
```

----

Quoting @pfmoore from Zulip:

> If a user installs something like tox, which depends directly on six, as well as indirectly via virtualenv, *and* the user has an older version of six installed, the current resolver sees the first dependency, notes that it's satisfies, and ignores the subsequent dependency. Result - virtualenv breaks because it wants to call a version of six that isn't installed.

Quoting myself:

> The current resolver would “successfully” resolve if you swap the packages to update (`pip install -U virtualenv "tox<3.14.4"`) because “first found wins”.

**Comment by uranusjr** [comment]
Two improvements (bugfixes?) are needed:

* Can’t find any links for PyYAML, but there are clearly compatible wheels. Need to investigate
* Need a way to provide dependencies for sdist-only projects. Two are known: `bokeh` and `toolz`.

**Comment by pradyunsg** [comment]
Another case: https://github.com/python-poetry/poetry/issues/2094

**Comment by uranusjr** [comment]
We’d probably want to add a timeout to the new resolver for the initial rollout, to avoid users waiting indefinitely. (If the resolver takes too long, give up and tell them to report the issue.)

**Comment by pradyunsg** [comment]
I think we should keep track of number of backtracks done, which would allow us to be insensitive to network latency, and the "oh, it's taking too long" would be dependent on the graph, rather than other system/external characteristics.

**Comment by uranusjr** [comment]
There’s currently not a hook to report how many backtrack steps were taken :p I think it would be acceptable to use “rounds” instead though, which counts forward steps.

**Comment by pradyunsg** [comment]
Pinging @sdispater for inputs here!

@sdispater Do you have any suggestions for here, other than `pyrax` and `oslo.utils` that you've seen?

I see user reports for things like `allennlp` and `newspaper3k` on poetry's issue tracker and I'm wondering if you remenber edge cases that you had to fix in poetry's resolver as part of user reports that aren't covered by the aforementioned cases.

**Comment by uranusjr** [comment]
I’m closing this since the repo has acquired several tests from pip users now. We can always add more when they come up.
