### ISSUE TITLE
Make it possible (for a reporter) to determine which candidate a requirement originates from

### ISSUE THREAD

**Issue by pradyunsg** [sarugaku/resolvelib#46]
This would be useful for reporters, to determine why a certain requirement is added. 

I'm imagining a `evaluating` hook, that's called at the start of the loop on `_attempt_to_pin_criterion`, prior to `pinning` but unconditionally (so that it doesn't actually have to match the criterion).

As an example, I want to be able to visualize false-starts / not-compatible-version checks, before they're pinned and currently, there's no way for the reporter to get this information.

**Comment by pradyunsg** [comment]
> an hard-coded assumption that `pinning` would be called after `adding_requirement`

Actually, this doesn't work for "root" requirements though.

**Comment by pradyunsg** [comment]
Alternatively, we could add a `evaluating` hook, that's called at the start of the loop on `_attempt_to_pin_criterion`.

**Comment by uranusjr** [comment]
I don’t like having too many hooks being called for a given code path. Would it be okay if a hook is added to report a candidate does not match? (i.e. for each candidate, either `pinning` or `ignoring` is called). Or maybe we can just renaming the `pinning` hook to something like `tried_to_pin(candidate: Candidate, success: bool)` and call it before the `continue`.

**Comment by techalchemy** [comment]
>  Or maybe we can just renaming the pinning hook to something like tried_to_pin(candidate: Candidate, success: bool)

I for one prefer this option, fwiw, since the naming is a lot easier to understand - although I can see the advantage of having two completely separate calls as well to avoid having to embed the conditional logic in the reporter.

**Comment by pradyunsg** [comment]
The other option is to add a `parent` argument to `Reporter.adding_requirement` -- the call site has the relevant information available to it.

**Comment by pradyunsg** [comment]
> Or maybe we can just renaming the `pinning` hook to something like `tried_to_pin(candidate: Candidate, success: bool)` and call it before the `continue`.

This doesn't make it possible to have all the information about which candidate the requirement originated from (see `adding  C==3.0.0` in the aforementioned output, which originates from `('B', <Version('2.0.0')>)`).

**Comment by uranusjr** [comment]
I can always pass in the requirements as well. How about

```python
tried_to_pin(requirements: List[Requirement], candidate: Optional[Candidate])
```

where `candidate` would be None on a failed pin?

**Comment by pradyunsg** [comment]
@uranusjr What would `List[Requirement]` be?

**Comment by uranusjr** [comment]
The requirements that the resolver tried to find the intersection on. But now I see that’s not what you want, but `parent` from the criteria?

I think I’ll go with the `parent` in `adding_requirement()` solution. That is the most straightforward conceptually for me. It’s getting muddy what exactly are needed right now, so many options have been proposed. Would you mind creating a PR adding the needed hooks for this solution?
