### ISSUE TITLE
Graph can miss edges

### ISSUE THREAD

**Issue by uranusjr** [sarugaku/resolvelib#5]
This sort here gets a list of (name, criterion) pairs. https://github.com/sarugaku/resolvelib/blob/f3174c8c20a4941c93cf037099deee2e08190af2/src/resolvelib/resolvers.py#L198-L216

The criterions, however, may change during the later loop. Since we made a copy here, criteria updated in the loop won’t be picked up until the next round, resulting in missed edges.

Example: A and B needs to be pinned in a round. B depends on A (we don’t know that yet until we pin B), and B is pinned before A.

* We make a copy of the current criteria. Those of A and B are both (say) empty.
* B is pinned. It has a child A, but since A is not yet pinned, it skips connecting to A, and leave A to connect.
* B contributes to A’s criterion. This updates `self._criteria['A']`, but not the copy made previously.
* A is pinned (in the same round). It uses the copied criterion, and does not know it should connect to B.

The solution is simple knowing what the problem is. Instead of cpoying `.items()`, only copy the key, and get the values lazily when we actually need it.

**Comment by techalchemy** [comment]
can you give an example of this?

**Comment by techalchemy** [comment]
(the part I'm not following is how wouldd B not know it has a child -- is that if B is abstract? How would it not learn of child A in the pinning round?)

**Comment by uranusjr** [comment]
So the pinning process is

1. Loop through each abstract requirement.
2. For each abstract requirement, loop through its possible concrete candidates, try whether one of them can be pinned.
3. For each concrete candidate, discover its dependencies and try to merge them with existing constraints. If the merge is successful, the candidate can be pinned.
4. Pin the said concrete candidate.

Since the dependencies of each concrete candidate are fetched lazily, when we try to pin it, we cannot know B depend on A before we reach B in the loop. My mistake was I read A’s constraints too eagerly, before reaching B, therefore even B correctly contributes to A’s constraints, the contribution is not picked up.
