### ISSUE TITLE
Backtrack on inconsistent candidate

### ISSUE THREAD

**Issue by uranusjr** [sarugaku/resolvelib#63]
Currently the resolver only allow one way for the provider to trigger backtracking, by supplying requirements (dependencies) that would empty a criterion’s candidate list. This prevents some oppertunities for applications to reject candidates in later stages. pip, for example, wants to reject a candidate with invalid/inconsistent metadata, but there’s currently no way for it to do this.

Except there is already a hook for that: `is_satisfied_by()`. This hook is already checked during pinning:

https://github.com/sarugaku/resolvelib/blob/4d6963a7505e8f4ab26641170e0e20aed44a38a7/src/resolvelib/resolvers.py#L205-L221

The first block catches `RequirementsConflicted`, which would be used to trigger backtracking. The second calls `is_satisfied_by()`, but expects it to always return True (otherwise raises `InconsistentCandidate`). If we modify the block to instead `continue` (i.e. give up on the candidate) when `is_satisfied()` returns false, the provider can then use it to validate the candidate and signal any latent issues that cannot be found previously.

This would help issues such as pypa/pip#9203, and provide the companion fix needed for pypa/pip#9199.

**Comment by uranusjr** [comment]
This may also help pypa/pip#9246.

**Comment by pradyunsg** [comment]
We ended up implementing this in pip's logic for this stuff.

**Comment by pradyunsg** [comment]
See https://github.com/pypa/pip/pull/9289 for the PR.
