### ISSUE TITLE
Avoid copying mapping and graph

### ISSUE THREAD

**Issue by pradyunsg** [sarugaku/resolvelib#7]
https://github.com/sarugaku/resolvelib/blob/f5e99b4f0d4ae28bd2e6ca709b56a365319ca39a/src/resolvelib/resolvers.py#L123-L126

In some preliminary testing and prior experience, copying results in both memory and run-time overhead.

**Comment by pradyunsg** [comment]
This isn't the right place for this discussion.

**Comment by uranusjr** [comment]
Not sure where the discussion will end up, so I’ll comment here for the moment. I don’t like this either, but it’s the fastest way to get a working thing at the moment. The resolver needs to roll back state when conflicts happen, and this takes the naive approach to store all states along the progress and roll back to an older one when it reaches a dead end. I guess it would be best to store things as diff sets and perform rollbacks in-place (i.e. svn vs git approach), but that would need a clear head and rigorous testing to get right.
