### ISSUE TITLE
Add info about how to run tests to README

### ISSUE THREAD

**Issue by jbylund** [sarugaku/resolvelib#83]
The first thing I look for in a README is how to install and run the test suite.

**Comment by uranusjr** [comment]
Fancy a pull request? You need to run two commands, this is the Travis configuration:

https://github.com/sarugaku/resolvelib/blob/19c09128394a4fddfd11c16c204a0f2246e98058/.travis.yml#L30-L32

**Comment by jbylund** [comment]
PR opened as #85.
